id: SOCRadarIncidents-Test
name: SOCRadarIncidents-Test
version: -1
fromversion: 6.0.0
starttaskid: '0'
tasks:
  '0':
    id: '0'
    taskid: '3b16f3c3-a81e-4c23-9398-8c33ca44b324'
    type: start
    task:
      id: '3b16f3c3-a81e-4c23-9398-8c33ca44b324'
      version: -1
      name: ''
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    view: '{"position": {"x": 50, "y": 50}}'
    note: false
    timertriggers: []
    ignoreworker: false
  '1':
    id: 1
    taskid: '5d56280f-ff4b-453c-8b0b-bd392bac416d'
    type: regular
    task:
      id: '5d56280f-ff4b-453c-8b0b-bd392bac416d'
      version: -1
      name: DeleteContext
      description: ''
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      all:
        simple: yes
    separatecontext: false
    view: '{"position": {"x": 50, "y": 200}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '2':
    id: 2
    taskid: '0b64d7d0-8450-4c95-944a-cda4668d15d5'
    type: regular
    task:
      id: '0b64d7d0-8450-4c95-944a-cda4668d15d5'
      version: -1
      name: socradar-mark-incident-fp
      description: ''
      script: '|||socradar-mark-incident-fp'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '3'
    scriptarguments: {}
    separatecontext: false
    view: '{"position": {"x": 50, "y": 400}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '3':
    id: 3
    taskid: '4dd274d8-66e1-4966-837e-3d2e39810b39'
    type: regular
    task:
      id: '4dd274d8-66e1-4966-837e-3d2e39810b39'
      version: -1
      name: socradar-mark-incident-resolved
      description: ''
      script: '|||socradar-mark-incident-resolved'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '4'
    scriptarguments: {}
    separatecontext: false
    view: '{"position": {"x": 50, "y": 600}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '4':
    id: '4'
    taskid: 'fcbbac85-e415-4008-8a7d-408d812c0b2f'
    type: title
    task:
      id: 'fcbbac85-e415-4008-8a7d-408d812c0b2f'
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ''
      description: ''
    separatecontext: false
    view: '{"position": {"x": 50, "y": 800}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
view: '{"linkLabelsPosition": {}, "paper": {"dimensions": {"height": 200, "width":
  380, "x": 50, "y": 50}}}'
inputs: []
outputs: []
description: ''
